language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install pep8
  - pip install MySQL-python
  - pip install wikitools
script:
  - cp settings.py.example settings.py
  - nosetests